### ISSUE TITLE
Buttons are not quite responsive (Galaxy Tab A 10")

### ISSUE THREAD

**Issue by davidgabriel42** [maxtonengineer/SafeTach-2-Project#10]
On 10” Galaxy Tab A, buttons are not quite responsive with tapping, user needs to find the right spot with multiple taps.
-Khai Ta

Are there specific buttons that are problematic?
-William G. Rothrock

RDM to implement bug fix. Maxton has clarified.
-William G. Rothrock

Additional testing required.
-David Gabriel

Verified
-David Gabriel

Issue seems to be intermittent. Will operate fine for some period of time, then has difficulty with buttons.
-David Gabriel

**Comment by maxtonengineer** [comment]
It looks like a potential cause of this issue is the touch screen sensitivity setting on Android tablets. By default, the sensitivity setting on Android tablets is set to 50%. A high sensitivity value means a larger touch area for a widget such as a button, and a smaller sensitivity value means you have to exactly hit the button to press it. I'm going to go ahead and set all of our Android tablets' sensitivity values to 100% and see if that resolves this issue. Note, this is exclusive to Android devices. On iOS devices, there's no way to adjust touch screen sensitivity. This blog goes into greater details explaining the touch screen sensitivity issue on Android devices.

https://www.inclusiveandroid.com/content/how-control-sensitivity-your-screen

Steps to adjust touch screen sensitivity levels on Android devices

1.  Tap settings.

2. Tap Language and Input

3. Scroll to the very bottom of these settings and tap pointer speed.

4. Increase the slider to make the touch screen more sensitive and easier to tab. Decrease the slider to make your touch screen less sensitive and more difficult to tap.

5. Tap OK and then experiment with the results.
